id: IEF8ED017
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T01:32:41+00:00'
last_modified: '2022-06-10T11:33:26.868610+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7013
  title: ས་སྐྱའི་གདན་རབས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    CBB0:
      image_group_id: I3CN7015
      title: ''
      total_pages: 288
      order: 1
      base_file: CBB0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
